name: NailVital Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Backend/requirements.txt
        
    - name: Run Backend API & Unit Tests
      run: |
        pytest Backend/test_api_unit.py

    - name: Run Selenium UI Tests
      run: |
        pytest tests/ui_website/test_website_ui.py
